import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import DarkMode from "@/components/dark-mode";

const jetbrains_mono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrains_mono.className} `}>
        <ThemeProvider
          attribute="Class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DarkMode />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
