import { Metadata } from "next";

import NavBar from "@/components/navbar";
import BoxBG from "@/components/boxBG";

export const metadata: Metadata = {
  title: "Devsphere",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <NavBar />
      <div
        style={{
          backgroundImage: `url(${BoxBG})`,
          backgroundPosition: "center",
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
        }}
      >
        <h1 className="w-full text-6xl">
          Open-Source and Blockchain fascinates us. Imagine a community that can
          assist you with that.
        </h1>
      </div>
    </>
  );
}
